// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rfw141/anr/gen/core"
	"github.com/rfw141/anr/pkg/app"
	"github.com/rfw141/anr/pkg/registry/etcd"
	"github.com/rfw141/anr/service/user/impl"
)

// Injectors from wire.go:

func initApp(config_Service *core.Config_Service, config_Registry *core.Config_Registry) (*app.App, func(), error) {
	userSvc := impl.NewUserSvc()
	server := impl.NewServer(config_Service, userSvc)
	client := etcd.NewEtcd(config_Registry)
	registrar := etcd.NewRegistrar(client, config_Registry)
	appApp := newApp(server, registrar)
	return appApp, func() {
	}, nil
}
