// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rfw141/anr/gen/core"
	"github.com/rfw141/anr/gen/svc/user/v1"
	"github.com/rfw141/anr/pkg/app"
	"github.com/rfw141/anr/pkg/registry/etcd"
	"github.com/rfw141/anr/service/admin/impl"
)

// Injectors from wire.go:

func initApp(config_Service *core.Config_Service, config_Registry *core.Config_Registry) (*app.App, func(), error) {
	client := etcd.NewEtcd(config_Registry)
	discovery := etcd.NewDiscovery(client, config_Registry)
	userServiceClient := v1.NewUserClient(discovery)
	adminService := impl.NewAdminService(userServiceClient)
	server := impl.NewServer(config_Service, adminService)
	registrar := etcd.NewRegistrar(client, config_Registry)
	appApp := newApp(server, registrar)
	return appApp, func() {
	}, nil
}
